### ISSUE TITLE
PHP license is not compliant Debian Free Software Guideline

### ISSUE THREAD

**Issue by knok** [saitoha/sixel#1]
Current (1.5.1) source includes php/ directory and it is under PHP 3.0 license.
Unfortunately, it is not acceptable on Debian because of "PHP" name restriction.

https://ftp-master.debian.org/REJECT-FAQ.html

Would you consider to  change the license to multi-license with another DFSG compliant
licenses like LGPL or MIT?

**Comment by saitoha** [comment]
@knok Oh, thanks for letting me realise about such an important thing.

**Comment by knok** [comment]
Thank you.
I'll upload it as a new debian package.
